### ISSUE TITLE
Submit plugin to the gradle plugin repository

### ISSUE THREAD

**Issue by mariusglauer** [cr0/gradle-macappbundle-plugin#1]
Hi, nice work!
It would be very nice, if you could submit your updated version of the macAppBundle plugin to the gradle repository.
See: http://plugins.gradle.org/submit

Thank you!

**Comment by cr0** [comment]
Jip I will of course add this plugin to bintray, however, I need to do some cleanup before I consider it publishable.

You can already try it using `gradle publishToMavenLocal` and add `mavenLocal()` as a repository in your gradle file.

**Comment by mariusglauer** [comment]
Thanks, I'll try that!

Edit: Just saw, that you already uploaded it to bintray. Adding `classpath 'com.github.cr0:gradle-macappbundle-plugin:3.0.0'` as a dependency and applying the plugin with `apply plugin: 'com.github.cr0.macappbundle'` worked for me.

**Comment by cr0** [comment]
It's now available at jcenter: https://plugins.gradle.org/plugin/com.github.cr0.macappbundle
