### ISSUE TITLE
Provide something more useful than "JRELoadError" when JRE needs to be updated

### ISSUE THREAD

**Issue by mariusglauer** [cr0/gradle-macappbundle-plugin#2]
Some of my users are still on Java 1.6 and therefore can't run my application which runs on Java 1.7. They are confused by the error message, which just says "JRELoadError".
![11059701_10202910280717615_4016125044306283506_n](https://cloud.githubusercontent.com/assets/1145196/7355749/2bb6b46c-ed24-11e4-9520-288a3e754837.jpg)

It would be very helpful, if there would be a short error description, which says that you need to download / update Java and then opens the Java download page in the user's browser.

**Comment by cr0** [comment]
Yep, at the moment there are no i18n language files. Thus, messages only display placeholders. Added to my todo list!
